name: Build and Test

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install

  trigger-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger UI Test Execution
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/dimosoftuni/lib-test/dispatches \
            -d '{"event_type": "trigger-ui-test"}'
